# Apache APISIX 3.x configuration for HealthOne TPA Claims Pipeline

apisix:
  node_listen: 9080
  enable_ipv6: false
  ssl:
    enable: true
    listen:
      - port: 9443
        enable_http2: true

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30
  admin:
    admin_listen:
      ip: "0.0.0.0"
      port: 9180
    allow_admin:
      - 0.0.0.0/0    # open for local dev; restrict to VPN/office CIDR in production
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

plugin_attr:
  prometheus:
    export_uri: /apisix/prometheus/metrics
    export_addr:
      ip: "0.0.0.0"
      port: 9091

plugins:
  - key-auth
  - limit-count
  - limit-req
  - prometheus
  - proxy-rewrite
  - response-rewrite
  - cors
  - request-id
  - echo
  - ip-restriction
  - jwt-auth
  - ua-restriction
  - redirect
